name: Publish NPM Package

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v6

      - run: npm ci

      - run: npm run build

      - run: npm adduser --scope=@jrs-custom --registry=https://registry.npmjs.org/

      - run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
